"""Added unique constraint for cloud shares

Revision ID: 108f85f77ecb
Revises: c7641ec0634
Create Date: 2015-05-21 14:29:20.586146

"""

# revision identifiers, used by Alembic.
revision = '108f85f77ecb'
down_revision = 'c7641ec0634'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_cloud_profiles_shares_profile_id'), 'cloud_profiles_shares', ['profile_id', 'name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_cloud_profiles_shares_profile_id'), 'cloud_profiles_shares', type_='unique')
    ### end Alembic commands ###
