"""Added usage tiers

Revision ID: 11c6801a8ad0
Revises: 252df6a434ff
Create Date: 2014-11-15 01:34:32.434947

"""

# revision identifiers, used by Alembic.
revision = '11c6801a8ad0'
down_revision = '252df6a434ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usagetiers', sa.Column('org_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usagetiers', 'org_id')
    ### end Alembic commands ###
