"""Removed user_repos from Tier

Revision ID: 1205af90e04d
Revises: 2aac1d0ee9a6
Create Date: 2015-01-28 16:53:37.883610

"""

# revision identifiers, used by Alembic.
revision = '1205af90e04d'
down_revision = '2aac1d0ee9a6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usagetiers', 'user_repos')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usagetiers', sa.Column('user_repos', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
