"""Renamed columns - from 'active' to 'enabled'

Revision ID: 1231d6a65b06
Revises: 27d11d1cf131
Create Date: 2015-02-04 18:57:52.623494

"""

# revision identifiers, used by Alembic.
revision = '1231d6a65b06'
down_revision = '27d11d1cf131'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikeys', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.drop_column('apikeys', 'active')
    op.add_column('organizations', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.drop_column('organizations', 'active')
    op.add_column('repositories', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('usagetiers', sa.Column('api_keys', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.drop_column('users', 'active')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'enabled')
    op.drop_column('usagetiers', 'api_keys')
    op.drop_column('repositories', 'enabled')
    op.add_column('organizations', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'enabled')
    op.add_column('apikeys', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('apikeys', 'enabled')
    ### end Alembic commands ###
