"""Added task runs

Revision ID: 133b6f6d6bee
Revises: 42194f438f00
Create Date: 2014-11-25 15:46:00.512732

"""

# revision identifiers, used by Alembic.
revision = '133b6f6d6bee'
down_revision = '42194f438f00'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskgroups', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'batch_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('batch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('taskgroups', 'batch_id')
    ### end Alembic commands ###
