"""empty message

Revision ID: 1743fe794118
Revises: 46f78b0312d3
Create Date: 2015-06-15 13:51:47.527136

"""

# revision identifiers, used by Alembic.
revision = '1743fe794118'
down_revision = '46f78b0312d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cronjobs', sa.Column('deployment_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'fk_cronjobs_revision_id_revisions', 'cronjobs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cronjobs_deployment_id_deployments'), 'cronjobs', 'deployments', ['deployment_id'], ['id'])
    op.drop_column('cronjobs', 'revision_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cronjobs', sa.Column('revision_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_cronjobs_deployment_id_deployments'), 'cronjobs', type_='foreignkey')
    op.create_foreign_key(u'fk_cronjobs_revision_id_revisions', 'cronjobs', 'revisions', ['revision_id'], ['id'])
    op.drop_column('cronjobs', 'deployment_id')
    ### end Alembic commands ###
