"""Added batch_id on Tasks

Revision ID: 1985a266efd9
Revises: 11c6801a8ad0
Create Date: 2014-11-18 17:16:14.702681

"""

# revision identifiers, used by Alembic.
revision = '1985a266efd9'
down_revision = '11c6801a8ad0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('batch_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'batch_id')
    ### end Alembic commands ###
