"""Added meta in Nodes

Revision ID: 19b660b41166
Revises: 43004beebacd
Create Date: 2014-09-23 16:44:00.121762

"""

# revision identifiers, used by Alembic.
revision = '19b660b41166'
down_revision = '43004beebacd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('meta', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'meta')
    ### end Alembic commands ###
