"""Added job.target_path

Revision ID: 1c5168f7d781
Revises: fbf25399add
Create Date: 2014-10-10 18:42:54.082046

"""

# revision identifiers, used by Alembic.
revision = '1c5168f7d781'
down_revision = 'fbf25399add'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('target_path', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'target_path')
    ### end Alembic commands ###
