"""Added task runs

Revision ID: 1d0cd32e9be2
Revises: 52bfb48b6a5
Create Date: 2014-11-24 17:36:19.363993

"""

# revision identifiers, used by Alembic.
revision = '1d0cd32e9be2'
down_revision = '52bfb48b6a5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=True),
    sa.Column('lang', sa.String(length=100), nullable=True),
    sa.Column('env_in', sa.Text(), nullable=True),
    sa.Column('env_out', sa.Text(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('full_script', sa.Text(), nullable=True),
    sa.Column('exec_start', sa.Integer(), nullable=True),
    sa.Column('exec_end', sa.Integer(), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_uuid'), 'runs', ['uuid'], unique=True)
    op.create_table('run_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('as_user', sa.String(length=200), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'tasks', sa.Column('exec_end', sa.Integer(), nullable=True))
    op.add_column(u'tasks', sa.Column('exec_start', sa.Integer(), nullable=True))
    op.drop_column(u'tasks', 'lang')
    op.drop_column(u'tasks', 'full_script')
    op.drop_column(u'tasks', 'total_steps')
    op.drop_column(u'tasks', 'exit_code')
    op.drop_column(u'tasks', 'step')
    op.drop_column(u'tasks', 'env_in')
    op.drop_column(u'tasks', 'env_out')
    op.drop_column(u'tasks', 'target')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'tasks', sa.Column('target', mysql.TEXT(), nullable=True))
    op.add_column(u'tasks', sa.Column('env_out', mysql.TEXT(), nullable=True))
    op.add_column(u'tasks', sa.Column('env_in', mysql.TEXT(), nullable=True))
    op.add_column(u'tasks', sa.Column('step', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'tasks', sa.Column('exit_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'tasks', sa.Column('total_steps', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'tasks', sa.Column('full_script', mysql.TEXT(), nullable=True))
    op.add_column(u'tasks', sa.Column('lang', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column(u'tasks', 'exec_start')
    op.drop_column(u'tasks', 'exec_end')
    op.drop_table('run_nodes')
    op.drop_index(op.f('ix_runs_uuid'), table_name='runs')
    op.drop_table('runs')
    ### end Alembic commands ###
