"""Added index to Task.script_name

Revision ID: 231b38dd9bab
Revises: 3113a8db2582
Create Date: 2015-04-30 15:18:46.908954

"""

# revision identifiers, used by Alembic.
revision = '231b38dd9bab'
down_revision = '3113a8db2582'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_script_name'), 'tasks', ['script_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_script_name'), table_name='tasks')
    ### end Alembic commands ###
