"""node reservations and ApiService

Revision ID: 24b5de6bb949
Revises: 2ba9ac1cbd43
Create Date: 2015-02-17 14:21:16.918470

"""

# revision identifiers, used by Alembic.
revision = '24b5de6bb949'
down_revision = '2ba9ac1cbd43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apiservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.Column('key', sa.String(length=1000), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], [u'organizations.id'], name=op.f('fk_apiservices_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apiservices'))
    )
    op.create_table('nodereservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('ssh_pubkey', sa.String(length=1000), nullable=True),
    sa.Column('disable_pass', sa.Boolean(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], [u'nodes.id'], name=op.f('fk_nodereservations_node_id_nodes')),
    sa.ForeignKeyConstraint(['service_id'], [u'apiservices.id'], name=op.f('fk_nodereservations_service_id_apiservices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodereservations'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodereservations')
    op.drop_table('apiservices')
    ### end Alembic commands ###
