"""Added usage tiers

Revision ID: 252df6a434ff
Revises: 46c01e41df77
Create Date: 2014-11-15 01:30:26.694124

"""

# revision identifiers, used by Alembic.
revision = '252df6a434ff'
down_revision = '46c01e41df77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usagetiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_repos', sa.Integer(), nullable=True),
    sa.Column('user_repos', sa.Integer(), nullable=True),
    sa.Column('external_repos', sa.Boolean(), nullable=True),
    sa.Column('nodes', sa.Integer(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('groups', sa.Integer(), nullable=True),
    sa.Column('roles', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usagetiers')
    ### end Alembic commands ###
