"""Added user.active

Revision ID: 2a6a7647b2fd
Revises: 4e08ddfc13f7
Create Date: 2014-09-24 18:00:48.266919

"""

# revision identifiers, used by Alembic.
revision = '2a6a7647b2fd'
down_revision = '4e08ddfc13f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    ### end Alembic commands ###
