"""Added description/enabled for ApiKey

Revision ID: 2aac1d0ee9a6
Revises: 44dd7b053ec1
Create Date: 2015-01-28 14:51:32.783446

"""

# revision identifiers, used by Alembic.
revision = '2aac1d0ee9a6'
down_revision = '44dd7b053ec1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikeys', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('apikeys', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('apikeys', sa.Column('last_used', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apikeys', 'last_used')
    op.drop_column('apikeys', 'description')
    op.drop_column('apikeys', 'active')
    ### end Alembic commands ###
