"""Removed unique index from repo

Revision ID: 2e455c06266d
Revises: 3dc43e8ace05
Create Date: 2015-03-20 12:56:42.659248

"""

# revision identifiers, used by Alembic.
revision = '2e455c06266d'
down_revision = '3dc43e8ace05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'uq_repositories_name', 'repositories', type_='unique')
    op.drop_index('uq_repositories_name', table_name='repositories')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_repositories_name', 'repositories', ['name'], unique=True)
    op.create_unique_constraint(u'uq_repositories_name', 'repositories', ['name'])
    ### end Alembic commands ###
