"""Added script_name in tasks

Revision ID: 3113a8db2582
Revises: 2e455c06266d
Create Date: 2015-04-29 12:52:11.700346

"""

# revision identifiers, used by Alembic.
revision = '3113a8db2582'
down_revision = '2e455c06266d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from cloudrunner_server.api.model import Task
_Session = sessionmaker()


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tasks', sa.Column('script_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###

    bind = op.get_bind()
    session = _Session(bind=bind)

    for task in session.query(Task).all():
        if task.script_content:
            task.script_name = task.script_content.script.full_path()
            session.add(task)
    session.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'script_name')
    ### end Alembic commands ###
