"""Added 'created_at' for folders

Revision ID: 362acdcdfb19
Revises: 1205af90e04d
Create Date: 2015-02-02 13:26:22.279235

"""

# revision identifiers, used by Alembic.
revision = '362acdcdfb19'
down_revision = '1205af90e04d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'created_at')
    ### end Alembic commands ###
