"""Change job reference to script

Revision ID: 385fe0811345
Revises: 1c5168f7d781
Create Date: 2014-10-12 18:16:12.831413

"""

# revision identifiers, used by Alembic.
revision = '385fe0811345'
down_revision = '1c5168f7d781'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('revision_id', sa.Integer(), nullable=True))
    op.drop_column('jobs', 'target_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('target_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'revision_id')
    ### end Alembic commands ###
