"""Added unique for user email

Revision ID: 3af2ecf9bfb4
Revises: 59b43d21fc57
Create Date: 2014-12-09 15:43:39.613609

"""

# revision identifiers, used by Alembic.
revision = '3af2ecf9bfb4'
down_revision = '59b43d21fc57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    ### end Alembic commands ###
