"""Added cloud_profiles quota

Revision ID: 3be0ad68817e
Revises: 56367006a5f2
Create Date: 2015-05-15 15:15:25.470647

"""

# revision identifiers, used by Alembic.
revision = '3be0ad68817e'
down_revision = '56367006a5f2'

from alembic import op
import sqlalchemy as sa

from sqlalchemy.orm import sessionmaker
from sqlalchemy.sql import table, column
_Session = sessionmaker()


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usagetiers', sa.Column(
        'cloud_profiles', sa.Integer(), nullable=True))
    op.add_column(
        'usagetiers', sa.Column('deployments', sa.Integer(), nullable=True))
    op.add_column('cloud_profiles', sa.Column(
        'enabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###
    tier = table('usagetiers', column('cloud_profiles', sa.Integer),
                 column('deployments', sa.Integer))
    profiles = table('cloud_profiles', column('enabled', sa.Boolean))

    op.execute(tier.update().values({'cloud_profiles': 20,
                                     'deployments': 20}))
    op.execute(profiles.update().values({'enabled': True}))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usagetiers', 'cloud_profiles')
    op.drop_column('usagetiers', 'deployments')
    op.drop_column('cloud_profiles', 'enabled')
    ### end Alembic commands ###
