"""Removed attached profile

Revision ID: 3bfae1b991e3
Revises: 5623f20d6445
Create Date: 2015-05-27 17:43:13.018645

"""

# revision identifiers, used by Alembic.
revision = '3bfae1b991e3'
down_revision = '5623f20d6445'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloud_attached_profiles')
    op.add_column('cloud_profiles', sa.Column('share_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_cloud_profiles_share_id_cloud_profiles'), 'cloud_profiles', 'cloud_profiles', ['share_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cloud_profiles_share_id_cloud_profiles'), 'cloud_profiles', type_='foreignkey')
    op.drop_column('cloud_profiles', 'share_id')
    op.create_table('cloud_attached_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('share_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], [u'users.id'], name=u'fk_cloud_attached_profiles_owner_id_users'),
    sa.ForeignKeyConstraint(['share_id'], [u'cloud_profiles_shares.id'], name=u'fk_cloud_attached_profiles_share_id_cloud_profiles_shares'),
    sa.PrimaryKeyConstraint('id', name=u'pk_cloud_attached_profiles')
    )
    ### end Alembic commands ###
