"""Added linked to Repository

Revision ID: 3dc43e8ace05
Revises: 53c6e060da0e
Create Date: 2015-03-20 12:25:29.346356

"""

# revision identifiers, used by Alembic.
revision = '3dc43e8ace05'
down_revision = '53c6e060da0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('linked_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_repositories_linked_id_repositories'), 'repositories', 'repositories', ['linked_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_repositories_linked_id_repositories'), 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'linked_id')
    ### end Alembic commands ###
