"""Dropping status column for Deployment

Revision ID: 404f345c3d37
Revises: 547d0297f7f3
Create Date: 2015-05-18 13:31:14.103197

"""

# revision identifiers, used by Alembic.
revision = '404f345c3d37'
down_revision = '547d0297f7f3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'status')
    op.execute('DROP TYPE status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('status', postgresql.ENUM(u'Pending', u'Started', u'Rebuilding',
                                                                     u'Patching', u'Stopped', u'Deleting', name='status'), autoincrement=False, nullable=True))
    ### end Alembic commands ###
