"""Added task runs

Revision ID: 42194f438f00
Revises: 1d0cd32e9be2
Create Date: 2014-11-25 11:17:59.205653

"""

# revision identifiers, used by Alembic.
revision = '42194f438f00'
down_revision = '1d0cd32e9be2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('exec_user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'exec_user_id')
    ### end Alembic commands ###
