"""Added step/total_steps in Task

Revision ID: 43004beebacd
Revises: 449b74b4f371
Create Date: 2014-09-18 15:53:55.246583

"""

# revision identifiers, used by Alembic.
revision = '43004beebacd'
down_revision = '449b74b4f371'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('step', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('total_steps', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'total_steps')
    op.drop_column('tasks', 'step')
    ### end Alembic commands ###
