"""Added full-script for Task

Revision ID: 449b74b4f371
Revises: 4507554a6d60
Create Date: 2014-09-17 16:53:45.885365

"""

# revision identifiers, used by Alembic.
revision = '449b74b4f371'
down_revision = '4507554a6d60'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('full_script', sa.Text(), nullable=True))
    op.drop_column('tasks', 'script_part')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('script_part', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'full_script')
    ### end Alembic commands ###
