"""Added uid for Jobs

Revision ID: 44dd7b053ec1
Revises: 4b7ff1b473c4
Create Date: 2014-12-18 12:28:35.291316

"""

# revision identifiers, used by Alembic.
revision = '44dd7b053ec1'
down_revision = '4b7ff1b473c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cronjobs', sa.Column('uid', sa.String(length=40), nullable=True))
    op.create_unique_constraint(op.f('uq_cronjobs_uid'), 'cronjobs', ['uid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_cronjobs_uid'), 'cronjobs', type_='unique')
    op.drop_column('cronjobs', 'uid')
    ### end Alembic commands ###
