"""Removed conditions

Revision ID: 46c01e41df77
Revises: 47390285bd29
Create Date: 2014-11-15 01:14:36.684133

"""

# revision identifiers, used by Alembic.
revision = '46c01e41df77'
down_revision = '47390285bd29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apikeys')
    ### end Alembic commands ###
