"""Added meta column for Revision

Revision ID: 46f78b0312d3
Revises: 43003fc2f2f4
Create Date: 2015-06-02 13:37:13.201031

"""

# revision identifiers, used by Alembic.
revision = '46f78b0312d3'
down_revision = '43003fc2f2f4'

from alembic import op
import sqlalchemy as sa

from sqlalchemy.orm import sessionmaker
from cloudrunner_server.api.model import Script
_Session = sessionmaker()


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'revisions', sa.Column('meta', sa.String(length=4000), nullable=True))
    bind = op.get_bind()
    session = _Session(bind=bind)

    for script in session.query(Script).all():
        if script.mime_type == 'text/workflow':
            script.mime_type == 'text/script'
            session.add(script)
    session.commit()

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions', 'meta')

    bind = op.get_bind()
    session = _Session(bind=bind)

    for script in session.query(Script).all():
        if script.mime_type == 'text/script':
            script.mime_type == 'text/workflow'
            session.add(script)
    session.commit()

    ### end Alembic commands ###
