"""Removed conditions

Revision ID: 47390285bd29
Revises: d85a59cc492
Create Date: 2014-11-15 01:00:29.053232

"""

# revision identifiers, used by Alembic.
revision = '47390285bd29'
down_revision = 'd85a59cc492'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scriptstep2batch')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scriptstep2batch',
    sa.Column('script_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('batch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], [u'batches.id'], name=u'scriptstep2batch_ibfk_1'),
    sa.ForeignKeyConstraint(['script_id'], [u'scriptsteps.id'], name=u'scriptstep2batch_ibfk_2'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
