"""Added trigger_types table

Revision ID: 480b3b1c7349
Revises: 1985a266efd9
Create Date: 2014-11-24 14:24:03.313644

"""

# revision identifiers, used by Alembic.
revision = '480b3b1c7349'
down_revision = '1985a266efd9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('arguments', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_types_name'), 'trigger_types', ['name'], unique=False)
    op.create_index(op.f('ix_trigger_types_type'), 'trigger_types', ['type'], unique=False)
    try:
        op.drop_column(u'tasks', 'started_by_id')
    except:
        pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'tasks', sa.Column('started_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_trigger_types_type'), table_name='trigger_types')
    op.drop_index(op.f('ix_trigger_types_name'), table_name='trigger_types')
    op.drop_table('trigger_types')
    ### end Alembic commands ###
