"""Added Server Id for nodes

Revision ID: 491ed17f9d5f
Revises: 3be0ad68817e
Create Date: 2015-05-18 12:30:36.030799

"""

# revision identifiers, used by Alembic.
revision = '491ed17f9d5f'
down_revision = '3be0ad68817e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('server_id', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'server_id')
    ### end Alembic commands ###
