"""Removed triggers, added cron jobs

Revision ID: 4b7ff1b473c4
Revises: 554527aefe1d
Create Date: 2014-12-17 16:10:49.850219

"""

# revision identifiers, used by Alembic.
revision = '4b7ff1b473c4'
down_revision = '554527aefe1d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cronjobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('exec_period', sa.String(length=100), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_cronjobs_owner_id_users')),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], name=op.f('fk_cronjobs_revision_id_revisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cronjobs')),
    sa.UniqueConstraint('name', 'owner_id', name='name__owner_id')
    )
    op.create_index(op.f('ix_cronjobs_name'), 'cronjobs', ['name'], unique=False)
    op.drop_table('jobs')
    op.drop_table('trigger_types')
    op.add_column('scripts', sa.Column('link_key', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'link_key')
    op.create_table('trigger_types',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('arguments', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], [u'tasks.id'], name=u'fk_trigger_types_task_id_tasks'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('jobs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('source', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('arguments', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('key', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('target_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('private', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('share_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('revision_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], [u'users.id'], name=u'fk_jobs_owner_id_users'),
    sa.ForeignKeyConstraint(['revision_id'], [u'revisions.id'], name=u'fk_jobs_revision_id_revisions'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_cronjobs_name'), table_name='cronjobs')
    op.drop_table('cronjobs')
    ### end Alembic commands ###
