"""Added AttachedProfiles

Revision ID: 4c8d6d058360
Revises: 3176f20feecd
Create Date: 2015-05-08 12:57:24.827698

"""

# revision identifiers, used by Alembic.
revision = '4c8d6d058360'
down_revision = '3176f20feecd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_attached_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], [u'users.id'], name=op.f('fk_cloud_attached_profiles_owner_id_users')),
    sa.ForeignKeyConstraint(['profile_id'], [u'cloud_profiles.id'], name=op.f('fk_cloud_attached_profiles_profile_id_cloud_profiles')),
    sa.ForeignKeyConstraint(['share_id'], [u'cloud_profiles_shares.id'], name=op.f('fk_cloud_attached_profiles_share_id_cloud_profiles_shares')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cloud_attached_profiles')),
    sa.UniqueConstraint('owner_id', 'share_id', name=op.f('uq_cloud_attached_profiles_owner_id'))
    )
    op.add_column(u'cloud_profiles', sa.Column('clear_nodes', sa.Boolean(), nullable=True))
    op.create_unique_constraint(op.f('uq_cloud_profiles_shares_name'), 'cloud_profiles_shares', ['name', 'password'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_cloud_profiles_shares_name'), 'cloud_profiles_shares', type_='unique')
    op.drop_column(u'cloud_profiles', 'clear_nodes')
    op.drop_table('cloud_attached_profiles')
    ### end Alembic commands ###
