"""Removed index

Revision ID: 4e08ddfc13f7
Revises: 584093c25828
Create Date: 2014-09-23 17:09:00.109008

"""

# revision identifiers, used by Alembic.
revision = '4e08ddfc13f7'
down_revision = '584093c25828'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'name', 'nodes', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'name', 'nodes', ['name'])
    ### end Alembic commands ###
