"""Added root/source to Batches table

Revision ID: 502527a432a2
Revises: 438821cb5fb5
Create Date: 2014-11-15 00:08:00.283367

"""

# revision identifiers, used by Alembic.
revision = '502527a432a2'
down_revision = '438821cb5fb5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scriptsteps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root', sa.Boolean(), nullable=True),
    sa.Column('as_sudo', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], [u'scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scriptstep2batch',
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scriptsteps.id'], )
    )
    op.drop_table('script2batch')
    op.add_column(u'batches', sa.Column('source_id', sa.Integer(), nullable=True))
    op.drop_column(u'conditions', 'dst_version')
    op.drop_column(u'conditions', 'src_version')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'conditions', sa.Column('src_version', mysql.VARCHAR(length=40), nullable=True))
    op.add_column(u'conditions', sa.Column('dst_version', mysql.VARCHAR(length=40), nullable=True))
    op.drop_column(u'batches', 'source_id')
    op.create_table('script2batch',
    sa.Column('script_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('batch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], [u'batches.id'], name=u'script2batch_ibfk_1'),
    sa.ForeignKeyConstraint(['script_id'], [u'scripts.id'], name=u'script2batch_ibfk_2'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('scriptstep2batch')
    op.drop_table('scriptsteps')
    ### end Alembic commands ###
