"""Added trigger_types table

Revision ID: 52bfb48b6a5
Revises: 480b3b1c7349
Create Date: 2014-11-24 14:28:05.796135

"""

# revision identifiers, used by Alembic.
revision = '52bfb48b6a5'
down_revision = '480b3b1c7349'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trigger_types', sa.Column('task_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trigger_types', 'task_id')
    ### end Alembic commands ###
