"""Added auto_cleanup to Nodes

Revision ID: 53c6e060da0e
Revises: 8fe25c3fe0d
Create Date: 2015-03-18 14:42:09.473174

"""

# revision identifiers, used by Alembic.
revision = '53c6e060da0e'
down_revision = '8fe25c3fe0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('auto_cleanup', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'auto_cleanup')
    ### end Alembic commands ###
