"""Added Deployments type

Revision ID: 53fe9cd577ed
Revises: 26890f2dbb
Create Date: 2015-05-15 12:59:02.949314

"""

# revision identifiers, used by Alembic.
revision = '53fe9cd577ed'
down_revision = '26890f2dbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_profiles', sa.Column('type', sa.String(length=25), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_profiles', 'type')
    ### end Alembic commands ###
