"""Added task.deployment field

Revision ID: 547d0297f7f3
Revises: 491ed17f9d5f
Create Date: 2015-05-18 13:19:57.386674

"""

# revision identifiers, used by Alembic.
revision = '547d0297f7f3'
down_revision = '491ed17f9d5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskgroups', sa.Column('deployment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_taskgroups_deployment_id_deployments'), 'taskgroups', 'deployments', ['deployment_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_taskgroups_deployment_id_deployments'), 'taskgroups', type_='foreignkey')
    op.drop_column('taskgroups', 'deployment_id')
    ### end Alembic commands ###
