"""Removed node.server_id

Revision ID: 5623f20d6445
Revises: 2610fe726b06
Create Date: 2015-05-22 16:41:21.906104

"""

# revision identifiers, used by Alembic.
revision = '5623f20d6445'
down_revision = '2610fe726b06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'server_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('server_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    ### end Alembic commands ###
