"""Added deploymentss quota

Revision ID: 56367006a5f2
Revises: 53fe9cd577ed
Create Date: 2015-05-15 14:25:08.728022

"""

# revision identifiers, used by Alembic.
revision = '56367006a5f2'
down_revision = '53fe9cd577ed'

from alembic import op
import sqlalchemy as sa

from sqlalchemy.orm import sessionmaker
from cloudrunner_server.api.model import UsageTier
_Session = sessionmaker()


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('usagetiers', sa.Column('deployments', sa.Integer(), nullable=True))

    bind = op.get_bind()
    session = _Session(bind=bind)

    for tier in session.query(UsageTier).all():
        tier.deployments = 20
    session.commit()

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usagetiers', 'deployments')
    op.drop_column('deployments', 'enabled')
    ### end Alembic commands ###
