"""Added AttachedProfiles

Revision ID: 5700eeaec0ed
Revises: 4c8d6d058360
Create Date: 2015-05-08 13:02:12.816981

"""

# revision identifiers, used by Alembic.
revision = '5700eeaec0ed'
down_revision = '4c8d6d058360'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'fk_cloud_attached_profiles_profile_id_cloud_profiles', 'cloud_attached_profiles', type_='foreignkey')
    op.drop_column('cloud_attached_profiles', 'profile_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_attached_profiles', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'fk_cloud_attached_profiles_profile_id_cloud_profiles', 'cloud_attached_profiles', 'cloud_profiles', ['profile_id'], ['id'])
    ### end Alembic commands ###
