"""Removed columns in Nodes

Revision ID: 584093c25828
Revises: 19b660b41166
Create Date: 2014-09-23 16:50:38.776170

"""

# revision identifiers, used by Alembic.
revision = '584093c25828'
down_revision = '19b660b41166'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'key_file')
    op.drop_column('nodes', 'cert_file')
    op.drop_column('nodes', 'csr_subject')
    op.drop_constraint(u'cert_file', 'nodes', type_='unique')
    op.drop_constraint(u'key_file', 'nodes', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'key_file', 'nodes', ['key_file'])
    op.create_unique_constraint(u'cert_file', 'nodes', ['cert_file'])
    op.add_column('nodes', sa.Column('csr_subject', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('nodes', sa.Column('cert_file', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('nodes', sa.Column('key_file', mysql.VARCHAR(length=512), nullable=True))
    ### end Alembic commands ###
