"""Added task runs

Revision ID: 59b43d21fc57
Revises: 133b6f6d6bee
Create Date: 2014-11-25 16:09:45.901484

"""

# revision identifiers, used by Alembic.
revision = '59b43d21fc57'
down_revision = '133b6f6d6bee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('exit_code', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'exit_code')
    ### end Alembic commands ###
