"""Added etag column for folders, scripts

Revision ID: 5ac452375150
Revises: 62289d3127c
Create Date: 2015-02-03 12:27:29.480190

"""

# revision identifiers, used by Alembic.
revision = '5ac452375150'
down_revision = '62289d3127c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('etag', sa.String(length=100), nullable=True))
    op.add_column('scripts', sa.Column('etag', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'etag')
    op.drop_column('folders', 'etag')
    ### end Alembic commands ###
