"""Removed link_key from scripts

Revision ID: 62289d3127c
Revises: 362acdcdfb19
Create Date: 2015-02-02 19:40:07.435010

"""

# revision identifiers, used by Alembic.
revision = '62289d3127c'
down_revision = '362acdcdfb19'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'link_key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('link_key', mysql.VARCHAR(length=50), nullable=True))
    ### end Alembic commands ###
