"""Test

Revision ID: 8fe25c3fe0d
Revises: 26dfc9dd5d52
Create Date: 2015-02-23 10:58:07.690784

"""

# revision identifiers, used by Alembic.
revision = '8fe25c3fe0d'
down_revision = '26dfc9dd5d52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_cronjobs_name'), 'cronjobs', ['name', 'owner_id'])
    op.create_unique_constraint(op.f('uq_folders_full_name'), 'folders', ['full_name', 'repository_id'])
    op.create_unique_constraint(op.f('uq_folders_name'), 'folders', ['name', 'parent_id'])
    op.create_unique_constraint(op.f('uq_groups_name'), 'groups', ['name', 'org_id'])
    op.create_unique_constraint(op.f('uq_nodegroups_name'), 'nodegroups', ['name', 'org_id'])
    op.create_unique_constraint(op.f('uq_nodes_name'), 'nodes', ['name', 'org_id'])
    op.create_unique_constraint(op.f('uq_repositories_org_id'), 'repositories', ['org_id', 'name'])
    op.create_unique_constraint(op.f('uq_revisions_script_id'), 'revisions', ['script_id', 'version'])
    op.create_unique_constraint(op.f('uq_scripts_name'), 'scripts', ['name', 'folder_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_scripts_name'), 'scripts', type_='unique')
    op.drop_constraint(op.f('uq_revisions_script_id'), 'revisions', type_='unique')
    op.drop_constraint(op.f('uq_repositories_org_id'), 'repositories', type_='unique')
    op.drop_constraint(op.f('uq_nodes_name'), 'nodes', type_='unique')
    op.drop_constraint(op.f('uq_nodegroups_name'), 'nodegroups', type_='unique')
    op.drop_constraint(op.f('uq_groups_name'), 'groups', type_='unique')
    op.drop_constraint(op.f('uq_folders_name'), 'folders', type_='unique')
    op.drop_constraint(op.f('uq_folders_full_name'), 'folders', type_='unique')
    op.drop_constraint(op.f('uq_cronjobs_name'), 'cronjobs', type_='unique')
    ### end Alembic commands ###
