"""Re-creating status column for Deployment

Revision ID: c7641ec0634
Revises: 404f345c3d37
Create Date: 2015-05-18 13:31:34.664028

"""

# revision identifiers, used by Alembic.
revision = 'c7641ec0634'
down_revision = '404f345c3d37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    status_type = sa.Enum('Pending', 'Starting', 'Running', 'Rebuilding', 'Patching', 'Stopping', 'Stopped', 'Deleting', name='status')
    status_type.create(op.get_bind(), checkfirst=False)
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('status', sa.Enum('Pending', 'Running', 'Started', 'Rebuilding', 'Patching', 'Stopping', 'Stopped', 'Deleting', name='status'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'status')
    op.execute('DROP TYPE status')
    ### end Alembic commands ###
