"""Added Node groups

Revision ID: cbd5e53d894
Revises: 385fe0811345
Create Date: 2014-10-18 18:01:42.233520

"""

# revision identifiers, used by Alembic.
revision = 'cbd5e53d894'
down_revision = '385fe0811345'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodegroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], [u'organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'org_id', name='name__org_id')
    )
    op.create_table('node2group',
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['nodegroups.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], )
    )
    op.drop_column(u'revisions', 'ext_source')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'revisions', sa.Column('ext_source', mysql.VARCHAR(length=500), nullable=True))
    op.drop_table('node2group')
    op.drop_table('nodegroups')
    ### end Alembic commands ###
