"""Removed conditions

Revision ID: d85a59cc492
Revises: 21cc9a522db4
Create Date: 2014-11-15 00:59:27.908100

"""

# revision identifiers, used by Alembic.
revision = 'd85a59cc492'
down_revision = '21cc9a522db4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scriptsteps', sa.Column('batch_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scriptsteps', 'batch_id')
    ### end Alembic commands ###
