"""Added repo.type

Revision ID: fbf25399add
Revises: 2a6a7647b2fd
Create Date: 2014-10-09 16:50:20.896695

"""

# revision identifiers, used by Alembic.
revision = 'fbf25399add'
down_revision = '2a6a7647b2fd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('type', sa.String(length=100), nullable=True))
    op.drop_column('repositories', 'is_link')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_link', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('repositories', 'type')
    ### end Alembic commands ###
