"""removed steps

Revision ID: 13ec3ef50267
Revises: c0d62558daa
Create Date: 2014-09-10 14:41:36.620620

"""

# revision identifiers, used by Alembic.
revision = '13ec3ef50267'
down_revision = 'c0d62558daa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps')
    op.add_column('tasks', sa.Column('env_in', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('env_out', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('lang', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('target', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'target')
    op.drop_column('tasks', 'lang')
    op.drop_column('tasks', 'env_out')
    op.drop_column('tasks', 'env_in')
    op.create_table('steps',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('job_id', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('target', mysql.TEXT(), nullable=True),
    sa.Column('timeout', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lang', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('script', mysql.TEXT(), nullable=True),
    sa.Column('env_in', mysql.TEXT(), nullable=True),
    sa.Column('env_out', mysql.TEXT(), nullable=True),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], [u'tasks.id'], name=u'steps_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
