"""Removed unused fields

Revision ID: 1e5b6279947a
Revises: 4f1ed96c9718
Create Date: 2014-08-23 01:59:30.608053

"""

# revision identifiers, used by Alembic.
revision = '1e5b6279947a'
down_revision = '4f1ed96c9718'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'name')
    op.create_unique_constraint(None, 'roles', ['as_user', 'servers', 'user_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles')
    op.add_column('roles', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    ### end Alembic commands ###
