"""Removed private field for scripts

Revision ID: 1f96fbb6cd64
Revises: 3409518444cd
Create Date: 2014-08-20 20:09:29.213693

"""

# revision identifiers, used by Alembic.
revision = '1f96fbb6cd64'
down_revision = '3409518444cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores')
    op.drop_column('scripts', 'private')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('private', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_table('stores',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('store_type', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
