"""Initial

Revision ID: 227f98a6d5f
Revises: None
Create Date: 2014-08-16 12:25:36.849925

"""

# revision identifiers, used by Alembic.
revision = '227f98a6d5f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
