"""Initial

Revision ID: 235f0648ddff
Revises: None
Create Date: 2014-09-05 11:41:42.042342

"""

# revision identifiers, used by Alembic.
revision = '235f0648ddff'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisions', sa.Column('draft', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions', 'draft')
    ### end Alembic commands ###
