"""Added Unique constraint for jobs.[name, owner_id]

Revision ID: 26ce3c80360c
Revises: 2936f003011a
Create Date: 2014-08-19 16:17:02.317958

"""

# revision identifiers, used by Alembic.
revision = '26ce3c80360c'
down_revision = '2936f003011a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_name', table_name='jobs')
    op.create_index(op.f('ix_jobs_name'), 'jobs', ['name'], unique=False)
    op.create_unique_constraint(None, 'jobs', ['name', 'owner_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs')
    op.drop_index(op.f('ix_jobs_name'), table_name='jobs')
    op.create_index('ix_jobs_name', 'jobs', ['name'], unique=True)
    ### end Alembic commands ###
