"""Added Node table approved column

Revision ID: 2a96ca58394a
Revises: 542e70b61088
Create Date: 2014-08-28 17:06:36.978801

"""

# revision identifiers, used by Alembic.
revision = '2a96ca58394a'
down_revision = '542e70b61088'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('approved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'approved')
    ### end Alembic commands ###
