"""Added Library/Folders

Revision ID: 3409518444cd
Revises: 50c7e7ed021e
Create Date: 2014-08-20 15:45:49.262133

"""

# revision identifiers, used by Alembic.
revision = '3409518444cd'
down_revision = '50c7e7ed021e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_link', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], [u'organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'org_id')
    )
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], [u'libraries.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name', 'library_id'),
    sa.UniqueConstraint('name', 'parent_id')
    )
    op.create_table('library_creds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('auth_user', sa.String(length=500), nullable=True),
    sa.Column('auth_pass', sa.String(length=500), nullable=True),
    sa.Column('auth_args', sa.String(length=500), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], [u'libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scripts', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.drop_column('scripts', 'store_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('scripts', 'folder_id')
    op.create_table('stores',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('store_type', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.drop_table('library_creds')
    op.drop_table('folders')
    op.drop_table('libraries')
    ### end Alembic commands ###
