"""Added trigger share url

Revision ID: 348287ebcd3f
Revises: 228cbfcdc43a
Create Date: 2014-08-27 18:22:23.184703

"""

# revision identifiers, used by Alembic.
revision = '348287ebcd3f'
down_revision = '228cbfcdc43a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('share_url', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'share_url')
    ### end Alembic commands ###
