"""Added tasks

Revision ID: 34b9d9dfcb9e
Revises: 897f5954ba4
Create Date: 2014-09-08 17:35:51.814736

"""

# revision identifiers, used by Alembic.
revision = '34b9d9dfcb9e'
down_revision = '897f5954ba4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', mysql.ENUM(u'Unknown', u'Running', u'Finished'), nullable=True))
    ### end Alembic commands ###
