"""Changed Script unique constraing

Revision ID: 367b4cf9380e
Revises: 1f96fbb6cd64
Create Date: 2014-08-22 14:35:35.654079

"""

# revision identifiers, used by Alembic.
revision = '367b4cf9380e'
down_revision = '1f96fbb6cd64'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rights')
    op.drop_constraint(u'name', 'scripts', type_='unique')
    op.create_unique_constraint(None, 'scripts', ['name', 'folder_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scripts')
    op.create_unique_constraint(u'name', 'scripts', ['name'])
    op.create_table('rights',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'rights_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('permissions')
    ### end Alembic commands ###
