"""Added exit_code to Tasks

Revision ID: 3a5b31bd680c
Revises: 3fa525ff5269
Create Date: 2014-09-08 17:22:51.208157

"""

# revision identifiers, used by Alembic.
revision = '3a5b31bd680c'
down_revision = '3fa525ff5269'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.add_column('tasks', sa.Column('exit_code', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'exit_code')
    op.create_table('logs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('exit_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timeout', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('step_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['step_id'], [u'steps.id'], name=u'logs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
