"""Added token scope

Revision ID: 3fa525ff5269
Revises: 414f8baf540f
Create Date: 2014-09-05 17:33:34.719130

"""

# revision identifiers, used by Alembic.
revision = '3fa525ff5269'
down_revision = '414f8baf540f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('started_by_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'started_by_id')
    ### end Alembic commands ###
