"""Initial

Revision ID: 404e74ef3b70
Revises: 235f0648ddff
Create Date: 2014-09-05 11:43:13.659472

"""

# revision identifiers, used by Alembic.
revision = '404e74ef3b70'
down_revision = '235f0648ddff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('draft', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('ext_source', sa.String(length=500), nullable=True),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_id', 'version', name='script_id__version')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revisions')
    ### end Alembic commands ###
