"""Added token scope

Revision ID: 414f8baf540f
Revises: 404e74ef3b70
Create Date: 2014-09-05 16:26:32.589539

"""

# revision identifiers, used by Alembic.
revision = '414f8baf540f'
down_revision = '404e74ef3b70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
