"""added script part

Revision ID: 42cce9a921d0
Revises: 13ec3ef50267
Create Date: 2014-09-11 13:45:45.850536

"""

# revision identifiers, used by Alembic.
revision = '42cce9a921d0'
down_revision = '13ec3ef50267'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('script_part', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'script_part')
    ### end Alembic commands ###
