"""Added tasks

Revision ID: 42e5d21e0cd3
Revises: 34b9d9dfcb9e
Create Date: 2014-09-08 17:35:58.051255

"""

# revision identifiers, used by Alembic.
revision = '42e5d21e0cd3'
down_revision = '34b9d9dfcb9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    ### end Alembic commands ###
