"""Another unique constraint for roles

Revision ID: 4d3e19887de6
Revises: 1e5b6279947a
Create Date: 2014-08-23 02:07:07.959970

"""

# revision identifiers, used by Alembic.
revision = '4d3e19887de6'
down_revision = '1e5b6279947a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['as_user', 'servers', 'group_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles')
    ### end Alembic commands ###
