"""Added unique for groups

Revision ID: 4f1ed96c9718
Revises: 17697ae585ce
Create Date: 2014-08-23 01:37:29.114036

"""

# revision identifiers, used by Alembic.
revision = '4f1ed96c9718'
down_revision = '17697ae585ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'groups', ['name', 'org_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups')
    ### end Alembic commands ###
