"""Added Job key column

Revision ID: 50c7e7ed021e
Revises: 26ce3c80360c
Create Date: 2014-08-19 19:28:01.270458

"""

# revision identifiers, used by Alembic.
revision = '50c7e7ed021e'
down_revision = '26ce3c80360c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('key', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'key')
    ### end Alembic commands ###
