"""Added library name unique constraint

Revision ID: 543b97cef93
Revises: 367b4cf9380e
Create Date: 2014-08-22 15:43:08.162250

"""

# revision identifiers, used by Alembic.
revision = '543b97cef93'
down_revision = '367b4cf9380e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'libraries', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'libraries')
    ### end Alembic commands ###
