"""Added Log source/source_type

Revision ID: 55d3e12cab31
Revises: 227f98a6d5f
Create Date: 2014-08-16 12:28:36.878190

"""

# revision identifiers, used by Alembic.
revision = '55d3e12cab31'
down_revision = '227f98a6d5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('source', sa.String(length=1000), nullable=True))
    op.add_column('logs', sa.Column('source_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'source_type')
    op.drop_column('logs', 'source')
    ### end Alembic commands ###
