"""Added tasks

Revision ID: 897f5954ba4
Revises: 3a5b31bd680c
Create Date: 2014-09-08 17:35:19.103641

"""

# revision identifiers, used by Alembic.
revision = '897f5954ba4'
down_revision = '3a5b31bd680c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
