"""Initial

Revision ID: c0d62558daa
Revises: 42e5d21e0cd3
Create Date: 2014-09-08 22:16:07.159357

"""

# revision identifiers, used by Alembic.
revision = 'c0d62558daa'
down_revision = '42e5d21e0cd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('timeout', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'timeout')
    ### end Alembic commands ###
